import type { DomainEvent } from "../../server/events/types.ts";
import type { WorkOrder } from "../../server/repositories/index.ts";
import { USER_ROLES } from "../../types/permissions.ts";

export function makeWorkOrder(workOrderId: string): WorkOrder {
  return {
    id: workOrderId,
    organizationId: "org-1",
    createdAt: "2026-05-06T08:00:00.000Z",
    updatedAt: "2026-05-06T08:00:00.000Z",
    createdByUserId: "manager-1",
    updatedByUserId: "manager-1",
    recordStatus: "active",
    isDeleted: false,
    deletedAt: null,
    deletedByUserId: null,
    tenantId: "org-1",
    workOrderNumber: `WO-${workOrderId.toUpperCase()}`,
    title: "Roof leak",
    description: "Roof leak in lobby",
    poNumber: null,
    requestedByName: null,
    requestedByEmail: null,
    requestedByPhone: null,
    requestedServiceDate: null,
    dueDate: null,
    category: null,
    requiresQuote: false,
    quoteRequiredThresholdCents: null,
    lifecycleStatus: "new",
    status: "new",
    assignmentStatus: null,
    quoteSummaryStatus: "not_required",
    invoiceSummaryStatus: "not_ready",
    approvalStatus: "not_required",
    priority: "high",
    clientOrganizationId: "client-1",
    locationId: "location-1",
    requestedByContactId: null,
    siteContactId: null,
    coordinatorUserId: null,
    managerUserId: null,
    assignedCoordinatorUserId: null,
    assignedManagerUserId: null,
    assignedContractorOrgId: null,
    assignedContractorContactId: null,
    financeOwnerUserId: null,
    quoteReviewerUserId: null,
    currentQuoteId: null,
    currentInvoiceId: null,
    currentQuoteVersionNumber: null,
    invoiceNumber: null,
    clientSnapshot: { id: "client-1", name: "Client One" },
    locationSnapshot: { id: "location-1", name: "Lobby", addressText: null },
    contractorSnapshot: null,
    lastActivityAt: "2026-05-06T08:00:00.000Z",
    nextActionOwnerType: null,
    nextActionDueAt: null,
    isEscalated: false,
    escalationReason: null,
    holdReason: null,
    previousLifecycleStatus: null,
    intakeReceivedAt: "2026-05-06T08:00:00.000Z",
    triagedAt: null,
    assignedAt: null,
    contractorContactedAt: null,
    contractorRespondedAt: null,
    workStartedAt: null,
    workCompletedAt: null,
    clientApprovedAt: null,
    closedAt: null,
    cancelledAt: null,
    onHoldAt: null,
    completedAt: null,
    priorityScore: null,
    dispatchZone: null,
    serviceLine: null,
    tradeCode: null,
    nteCents: null,
    metadata: {},
  } as WorkOrder;
}

export function makeWorkOrderCreatedEvent(
  eventId: string,
  workOrderId: string,
): DomainEvent<"work_order_created"> {
  return {
    id: eventId,
    organizationId: "org-1",
    tenantId: "org-1",
    workOrderId,
    type: "work_order_created",
    actor: {
      actorId: "coordinator-1",
      actorType: "user",
      actorRole: USER_ROLES.Coordinator,
      displayName: "Coordinator One",
    },
    visibility: "internal",
    occurredAt: "2026-05-06T09:00:00.000Z",
    lifecycleStatus: "new",
    entity: {
      entityType: "work_order",
      entityId: workOrderId,
      label: workOrderId.toUpperCase(),
    },
    summary: "Work order created.",
    metadata: {
      requestId: `req-${eventId}`,
      reason: null,
      correlationId: `corr-${workOrderId}`,
      details: {},
    },
    payload: {
      lifecycleStatus: "new",
      priority: "high",
      title: "Roof leak",
    },
  };
}

export function makeInternalMessageEvent(
  eventId: string,
  workOrderId: string,
  occurredAt = "2026-05-06T09:29:00.000Z",
): DomainEvent<"communication_message_created"> {
  return {
    id: eventId,
    organizationId: "org-1",
    tenantId: "org-1",
    workOrderId,
    type: "communication_message_created",
    actor: {
      actorId: "manager-1",
      actorType: "user",
      actorRole: USER_ROLES.Manager,
      displayName: "Manager One",
    },
    visibility: "internal",
    occurredAt,
    lifecycleStatus: "new",
    entity: {
      entityType: "communication_message",
      entityId: `msg-${eventId}`,
      label: "Internal note",
    },
    summary: "Created internal note.",
    metadata: {
      requestId: `req-${eventId}`,
      reason: null,
      correlationId: `corr-${workOrderId}`,
      details: {},
    },
    payload: {
      threadId: `thread-${workOrderId}`,
      messageId: `msg-${eventId}`,
      channel: "internal_note",
      direction: "internal",
    },
  };
}
