import "server-only";

import type { EntityId } from "@/types/entity";
import type {
  AiIntakeDraft,
  IntakeApproval,
  IntakeArtifact,
  IntakeDecision,
  IntakeEvent,
} from "@/modules/intake";
import type {
  CommunicationAttachment,
  CommunicationLink,
  CommunicationMatchSuggestion,
  CommunicationMessage,
  CommunicationParticipant,
  CommunicationThread,
} from "@/modules/communications";
import type {
  ProviderConnection,
  ProviderMessageReceipt,
  ProviderSyncCheckpoint,
  ProviderSyncRun,
  ProviderThreadMapping,
} from "@/modules/providers";
import type {
  EventProcessingRecord,
  WorkerDeadLetterRecord,
  WorkerJob,
} from "@/modules/runtime";
import type { DeliveryPlan as CanonicalDeliveryPlan } from "@/modules/delivery";
import type { EscalationOrchestration, EscalationStage } from "@/modules/escalation";
import type { DeliveryAttempt } from "@/modules/transport";
import type { SlaScanCursor, SlaTimer } from "@/modules/sla";
import {
  toFirestoreTimestamp,
  toIsoDateTime,
  toNullableFirestoreTimestamp,
  toNullableIsoDateTime,
} from "@/server/repositories/firestore/timestamps";
import type {
  ActivityLog,
  ActivityLogDocument,
  AiIntakeDraftDocument,
  Assignment,
  AssignmentDocument,
  ClientOrganizationContactLink,
  ClientOrganizationContactLinkDocument,
  ClientInvoice,
  ClientInvoiceDocument,
  ClientOrganization,
  ClientOrganizationDocument,
  ClientQuote,
  ClientQuoteDocument,
  CommunicationAttachmentDocument,
  CommunicationLinkDocument,
  CommunicationMatchSuggestionDocument,
  CommunicationMessageDocument,
  CommunicationParticipantDocument,
  CommunicationThreadDocument,
  Contact,
  ContactDocument,
  ContractorContactLink,
  ContractorContactLinkDocument,
  ContractorQuote,
  ContractorQuoteDocument,
  ContractorOrganization,
  ContractorOrganizationDocument,
  DeliveryAttemptDocument,
  DeliveryPlanDocument,
  DomainAuditFields,
  FirestoreAuditFields,
  InternalNotification,
  InternalNotificationDocument,
  IntakeApprovalDocument,
  IntakeArtifactDocument,
  IntakeDecisionDocument,
  IntakeEventDocument,
  DomainEventDocument,
  EscalationOrchestrationDocument,
  EventProcessingDocument,
  ProviderConnectionDocument,
  ProviderMessageReceiptDocument,
  ProviderSyncCheckpointDocument,
  ProviderSyncRunDocument,
  ProviderThreadMappingDocument,
  SlaScanCursorDocument,
  SlaTimerDocument,
  WorkerDeadLetterDocument,
  WorkerJobDocument,
  Location,
  LocationContactLink,
  LocationContactLinkDocument,
  LocationDocument,
  TransitionAuditDocument,
  TransitionEventDocument,
  UserProfile,
  UserProfileDocument,
  WorkOrder,
  WorkOrderDocument,
} from "@/server/repositories/firestore/models";
import type {
  DomainEvent,
  TransitionAudit,
  TransitionEvent,
} from "@/server/events/types";

export interface FirestoreEntityMapper<TDomain, TDocument> {
  toDomain(id: EntityId, document: TDocument): TDomain;
  toDocument(domain: TDomain): TDocument;
}

export const userProfileMapper: FirestoreEntityMapper<
  UserProfile,
  UserProfileDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    email: document.email,
    displayName: document.displayName,
    role: document.role,
    status: document.status,
    clientOrganizationId: document.clientOrganizationId,
    contractorOrganizationId: document.contractorOrganizationId,
    locationIds: document.locationIds,
    lastLoginAt: toNullableIsoDateTime(document.lastLoginAt, "lastLoginAt"),
  }),
  toDocument: (entity) => {
    const { lastLoginAt, ...domain } = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      email: domain.email,
      displayName: domain.displayName,
      role: domain.role,
      status: domain.status,
      clientOrganizationId: domain.clientOrganizationId,
      contractorOrganizationId: domain.contractorOrganizationId,
      locationIds: domain.locationIds,
      lastLoginAt: toNullableFirestoreTimestamp(lastLoginAt),
    };
  },
};

export const contactMapper: FirestoreEntityMapper<Contact, ContactDocument> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    firstName: document.firstName,
    lastName: document.lastName,
    displayName: document.displayName,
    email: document.email ?? null,
    primaryPhone: document.primaryPhone ?? null,
    secondaryPhone: document.secondaryPhone ?? null,
    roleTitle: document.roleTitle ?? null,
    preferredLanguage: document.preferredLanguage,
    preferredContactMethod: document.preferredContactMethod ?? null,
    notes: document.notes ?? null,
    status: document.status,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      firstName: domain.firstName,
      lastName: domain.lastName,
      displayName: domain.displayName,
      email: domain.email ?? null,
      primaryPhone: domain.primaryPhone ?? null,
      secondaryPhone: domain.secondaryPhone ?? null,
      roleTitle: domain.roleTitle ?? null,
      preferredLanguage: domain.preferredLanguage,
      preferredContactMethod: domain.preferredContactMethod ?? null,
      notes: domain.notes ?? null,
      status: domain.status,
    };
  },
};

export const clientOrganizationMapper: FirestoreEntityMapper<
  ClientOrganization,
  ClientOrganizationDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    name: document.name,
    displayName: document.displayName,
    status: document.status,
    primaryContactId: document.primaryContactId ?? null,
    billingContactId: document.billingContactId ?? null,
    notes: document.notes,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      name: domain.name,
      displayName: domain.displayName,
      status: domain.status,
      primaryContactId: domain.primaryContactId ?? null,
      billingContactId: domain.billingContactId ?? null,
      notes: domain.notes,
    };
  },
};

export const locationMapper: FirestoreEntityMapper<Location, LocationDocument> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    clientOrganizationId: document.clientOrganizationId,
    name: document.name,
    displayName: document.displayName ?? null,
    code: document.code,
    storeNumber: document.storeNumber ?? null,
    status: document.status,
    primaryContactId: document.primaryContactId ?? null,
    siteContactId: document.siteContactId ?? null,
    addressLine1: document.addressLine1,
    addressLine2: document.addressLine2,
    city: document.city,
    region: document.region,
    postalCode: document.postalCode,
    countryCode: document.countryCode,
    latitude: document.latitude ?? null,
    longitude: document.longitude ?? null,
    timeZone: document.timeZone ?? null,
    accessNotes: document.accessNotes,
    serviceNotes: document.serviceNotes ?? null,
    notes: document.notes,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      clientOrganizationId: domain.clientOrganizationId,
      name: domain.name,
      displayName: domain.displayName ?? null,
      code: domain.code,
      storeNumber: domain.storeNumber ?? null,
      status: domain.status,
      primaryContactId: domain.primaryContactId ?? null,
      siteContactId: domain.siteContactId ?? null,
      addressLine1: domain.addressLine1,
      addressLine2: domain.addressLine2,
      city: domain.city,
      region: domain.region,
      postalCode: domain.postalCode,
      countryCode: domain.countryCode,
      latitude: domain.latitude ?? null,
      longitude: domain.longitude ?? null,
      timeZone: domain.timeZone ?? null,
      accessNotes: domain.accessNotes,
      serviceNotes: domain.serviceNotes ?? null,
      notes: domain.notes,
    };
  },
};

export const contractorOrganizationMapper: FirestoreEntityMapper<
  ContractorOrganization,
  ContractorOrganizationDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    name: document.name,
    displayName: document.displayName,
    parentContractorId: document.parentContractorId ?? null,
    status: document.status,
    isAssignable: document.isAssignable ?? undefined,
    primaryContactId: document.primaryContactId ?? null,
    billingContactId: document.billingContactId ?? null,
    dispatchContactId: document.dispatchContactId ?? null,
    businessEmail: document.businessEmail ?? null,
    mainPhone: document.mainPhone ?? null,
    altPhone: document.altPhone ?? null,
    fax: document.fax ?? null,
    trades: document.trades ?? [],
    serviceArea: document.serviceArea ?? null,
    ratingSummary:
      document.ratingSummary == null
        ? null
        : {
            averageRating: document.ratingSummary.averageRating,
            reviewCount: document.ratingSummary.reviewCount,
            lastReviewedAt: toNullableIsoDateTime(
              document.ratingSummary.lastReviewedAt ?? null,
              "contractorOrganization.ratingSummary.lastReviewedAt",
            ),
          },
    addressLine1: document.addressLine1 ?? null,
    addressLine2: document.addressLine2 ?? null,
    city: document.city ?? null,
    region: document.region ?? null,
    postalCode: document.postalCode ?? null,
    countryCode: document.countryCode ?? null,
    notes: document.notes,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      name: domain.name,
      displayName: domain.displayName,
      parentContractorId: domain.parentContractorId ?? null,
      status: domain.status,
      isAssignable: domain.isAssignable ?? undefined,
      primaryContactId: domain.primaryContactId ?? null,
      billingContactId: domain.billingContactId ?? null,
      dispatchContactId: domain.dispatchContactId ?? null,
      businessEmail: domain.businessEmail ?? null,
      mainPhone: domain.mainPhone ?? null,
      altPhone: domain.altPhone ?? null,
      fax: domain.fax ?? null,
      trades: domain.trades ?? [],
      serviceArea: domain.serviceArea ?? null,
      ratingSummary:
        domain.ratingSummary == null
          ? null
          : {
              averageRating: domain.ratingSummary.averageRating,
              reviewCount: domain.ratingSummary.reviewCount,
              lastReviewedAt: toNullableFirestoreTimestamp(
                domain.ratingSummary.lastReviewedAt ?? null,
              ),
            },
      addressLine1: domain.addressLine1 ?? null,
      addressLine2: domain.addressLine2 ?? null,
      city: domain.city ?? null,
      region: domain.region ?? null,
      postalCode: domain.postalCode ?? null,
      countryCode: domain.countryCode ?? null,
      notes: domain.notes,
    };
  },
};

export const clientOrganizationContactLinkMapper: FirestoreEntityMapper<
  ClientOrganizationContactLink,
  ClientOrganizationContactLinkDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    clientOrganizationId: document.clientOrganizationId,
    contactId: document.contactId,
    relationshipType: document.relationshipType,
    isPrimary: document.isPrimary,
    notes: document.notes ?? null,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      clientOrganizationId: domain.clientOrganizationId,
      contactId: domain.contactId,
      relationshipType: domain.relationshipType,
      isPrimary: domain.isPrimary,
      notes: domain.notes ?? null,
    };
  },
};

export const locationContactLinkMapper: FirestoreEntityMapper<
  LocationContactLink,
  LocationContactLinkDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    locationId: document.locationId,
    contactId: document.contactId,
    relationshipType: document.relationshipType,
    isPrimary: document.isPrimary,
    notes: document.notes ?? null,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      locationId: domain.locationId,
      contactId: domain.contactId,
      relationshipType: domain.relationshipType,
      isPrimary: domain.isPrimary,
      notes: domain.notes ?? null,
    };
  },
};

export const contractorContactLinkMapper: FirestoreEntityMapper<
  ContractorContactLink,
  ContractorContactLinkDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    contractorId: document.contractorId,
    contactId: document.contactId,
    relationshipType: document.relationshipType,
    isPrimary: document.isPrimary,
    notes: document.notes ?? null,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      contractorId: domain.contractorId,
      contactId: domain.contactId,
      relationshipType: domain.relationshipType,
      isPrimary: domain.isPrimary,
      notes: domain.notes ?? null,
    };
  },
};

export const workOrderMapper: FirestoreEntityMapper<WorkOrder, WorkOrderDocument> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    workOrderNumber: document.workOrderNumber,
    title: document.title,
    description: document.description,
    poNumber: document.poNumber ?? null,
    requestedByName: document.requestedByName ?? null,
    requestedByEmail: document.requestedByEmail ?? null,
    requestedByPhone: document.requestedByPhone ?? null,
    requestedServiceDate: toNullableIsoDateTime(
      document.requestedServiceDate,
      "requestedServiceDate",
    ),
    dueDate: toNullableIsoDateTime(document.dueDate, "dueDate"),
    category: document.category ?? null,
    requiresQuote: document.requiresQuote ?? false,
    quoteRequiredThresholdCents: document.quoteRequiredThresholdCents ?? null,
    lifecycleStatus: document.lifecycleStatus,
    status: document.lifecycleStatus,
    assignmentStatus: document.assignmentStatus ?? null,
    quoteSummaryStatus: document.quoteSummaryStatus ?? null,
    invoiceSummaryStatus: document.invoiceSummaryStatus ?? null,
    approvalStatus: document.approvalStatus ?? null,
    priority: document.priority,
    clientOrganizationId: document.clientOrganizationId,
    locationId: document.locationId,
    requestedByContactId: document.requestedByContactId ?? null,
    siteContactId: document.siteContactId ?? null,
    coordinatorUserId: document.coordinatorUserId ?? null,
    managerUserId: document.managerUserId ?? null,
    assignedCoordinatorUserId: document.assignedCoordinatorUserId ?? null,
    assignedManagerUserId: document.assignedManagerUserId ?? null,
    assignedContractorOrgId: document.assignedContractorOrgId ?? null,
    assignedContractorId: document.assignedContractorOrgId ?? null,
    assignedContractorContactId: document.assignedContractorContactId ?? null,
    financeOwnerUserId: document.financeOwnerUserId ?? null,
    quoteReviewerUserId: document.quoteReviewerUserId ?? null,
    currentQuoteId: document.currentQuoteId ?? null,
    currentInvoiceId: document.currentInvoiceId ?? null,
    currentQuoteVersionNumber: document.currentQuoteVersionNumber ?? null,
    invoiceNumber: document.invoiceNumber ?? null,
    clientSnapshot: document.clientSnapshot,
    locationSnapshot: document.locationSnapshot,
    contractorSnapshot: document.contractorSnapshot ?? null,
    lastActivityAt: toNullableIsoDateTime(document.lastActivityAt, "lastActivityAt"),
    nextActionOwnerType: document.nextActionOwnerType ?? null,
    nextActionDueAt: toNullableIsoDateTime(
      document.nextActionDueAt,
      "nextActionDueAt",
    ),
    isEscalated: document.isEscalated ?? false,
    escalationReason: document.escalationReason ?? null,
    holdReason: document.holdReason ?? null,
    previousLifecycleStatus: document.previousLifecycleStatus ?? null,
    intakeReceivedAt: toNullableIsoDateTime(document.intakeReceivedAt, "intakeReceivedAt"),
    submittedAt: toNullableIsoDateTime(document.intakeReceivedAt, "intakeReceivedAt"),
    triagedAt: toNullableIsoDateTime(document.triagedAt, "triagedAt"),
    assignedAt: toNullableIsoDateTime(document.assignedAt, "assignedAt"),
    contractorContactedAt: toNullableIsoDateTime(
      document.contractorContactedAt,
      "contractorContactedAt",
    ),
    contractorRespondedAt: toNullableIsoDateTime(
      document.contractorRespondedAt,
      "contractorRespondedAt",
    ),
    contractorScheduledAt: toNullableIsoDateTime(
      document.contractorScheduledAt,
      "contractorScheduledAt",
    ),
    workStartedAt: toNullableIsoDateTime(document.workStartedAt, "workStartedAt"),
    quoteRequestedAt: toNullableIsoDateTime(document.quoteRequestedAt, "quoteRequestedAt"),
    contractorQuoteReceivedAt: toNullableIsoDateTime(
      document.contractorQuoteReceivedAt,
      "contractorQuoteReceivedAt",
    ),
    quoteReviewStartedAt: toNullableIsoDateTime(
      document.quoteReviewStartedAt,
      "quoteReviewStartedAt",
    ),
    clientApprovalRequestedAt: toNullableIsoDateTime(
      document.clientApprovalRequestedAt,
      "clientApprovalRequestedAt",
    ),
    clientApprovedAt: toNullableIsoDateTime(document.clientApprovedAt, "clientApprovedAt"),
    approvedAt: toNullableIsoDateTime(document.clientApprovedAt, "clientApprovedAt"),
    workCompletedAt: toNullableIsoDateTime(document.workCompletedAt, "workCompletedAt"),
    completedAt: toNullableIsoDateTime(document.workCompletedAt, "workCompletedAt"),
    completionReviewStartedAt: toNullableIsoDateTime(
      document.completionReviewStartedAt,
      "completionReviewStartedAt",
    ),
    readyForInvoicingAt: toNullableIsoDateTime(
      document.readyForInvoicingAt,
      "readyForInvoicingAt",
    ),
    invoiceSentAt: toNullableIsoDateTime(document.invoiceSentAt, "invoiceSentAt"),
    paidAt: toNullableIsoDateTime(document.paidAt, "paidAt"),
    closedAt: toNullableIsoDateTime(document.closedAt, "closedAt"),
    cancelledAt: toNullableIsoDateTime(document.cancelledAt, "cancelledAt"),
    holdStartedAt: toNullableIsoDateTime(document.holdStartedAt, "holdStartedAt"),
    escalatedAt: toNullableIsoDateTime(document.escalatedAt, "escalatedAt"),
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      workOrderNumber: domain.workOrderNumber,
      title: domain.title,
      description: domain.description,
      poNumber: domain.poNumber ?? null,
      requestedByName: domain.requestedByName ?? null,
      requestedByEmail: domain.requestedByEmail ?? null,
      requestedByPhone: domain.requestedByPhone ?? null,
      requestedServiceDate: toNullableFirestoreTimestamp(
        domain.requestedServiceDate,
      ),
      dueDate: toNullableFirestoreTimestamp(domain.dueDate),
      category: domain.category ?? null,
      requiresQuote: domain.requiresQuote ?? false,
      quoteRequiredThresholdCents: domain.quoteRequiredThresholdCents ?? null,
      lifecycleStatus: domain.lifecycleStatus,
      assignmentStatus: domain.assignmentStatus ?? null,
      quoteSummaryStatus: domain.quoteSummaryStatus ?? null,
      invoiceSummaryStatus: domain.invoiceSummaryStatus ?? null,
      approvalStatus: domain.approvalStatus ?? null,
      priority: domain.priority,
      clientOrganizationId: domain.clientOrganizationId,
      locationId: domain.locationId,
      requestedByContactId: domain.requestedByContactId ?? null,
      siteContactId: domain.siteContactId ?? null,
      coordinatorUserId: domain.coordinatorUserId ?? null,
      managerUserId: domain.managerUserId ?? null,
      assignedCoordinatorUserId: domain.assignedCoordinatorUserId ?? null,
      assignedManagerUserId: domain.assignedManagerUserId ?? null,
      assignedContractorOrgId: domain.assignedContractorOrgId ?? null,
      assignedContractorId: domain.assignedContractorId ?? null,
      assignedContractorContactId: domain.assignedContractorContactId ?? null,
      financeOwnerUserId: domain.financeOwnerUserId ?? null,
      quoteReviewerUserId: domain.quoteReviewerUserId ?? null,
      currentQuoteId: domain.currentQuoteId ?? null,
      currentInvoiceId: domain.currentInvoiceId ?? null,
      currentQuoteVersionNumber: domain.currentQuoteVersionNumber ?? null,
      invoiceNumber: domain.invoiceNumber ?? null,
      clientSnapshot: domain.clientSnapshot,
      locationSnapshot: domain.locationSnapshot,
      contractorSnapshot: domain.contractorSnapshot ?? null,
      lastActivityAt: toNullableFirestoreTimestamp(domain.lastActivityAt),
      nextActionOwnerType: domain.nextActionOwnerType ?? null,
      nextActionDueAt: toNullableFirestoreTimestamp(domain.nextActionDueAt),
      isEscalated: domain.isEscalated ?? false,
      escalationReason: domain.escalationReason ?? null,
      holdReason: domain.holdReason ?? null,
      previousLifecycleStatus: domain.previousLifecycleStatus ?? null,
      intakeReceivedAt: toNullableFirestoreTimestamp(domain.intakeReceivedAt),
      submittedAt: toNullableFirestoreTimestamp(domain.submittedAt ?? null),
      triagedAt: toNullableFirestoreTimestamp(domain.triagedAt),
      assignedAt: toNullableFirestoreTimestamp(domain.assignedAt),
      contractorContactedAt: toNullableFirestoreTimestamp(domain.contractorContactedAt),
      contractorRespondedAt: toNullableFirestoreTimestamp(domain.contractorRespondedAt),
      contractorScheduledAt: toNullableFirestoreTimestamp(domain.contractorScheduledAt),
      workStartedAt: toNullableFirestoreTimestamp(domain.workStartedAt),
      quoteRequestedAt: toNullableFirestoreTimestamp(domain.quoteRequestedAt),
      contractorQuoteReceivedAt: toNullableFirestoreTimestamp(
        domain.contractorQuoteReceivedAt,
      ),
      quoteReviewStartedAt: toNullableFirestoreTimestamp(domain.quoteReviewStartedAt),
      clientApprovalRequestedAt: toNullableFirestoreTimestamp(
        domain.clientApprovalRequestedAt,
      ),
      clientApprovedAt: toNullableFirestoreTimestamp(domain.clientApprovedAt),
      approvedAt: toNullableFirestoreTimestamp(
        domain.approvedAt ?? domain.clientApprovedAt ?? null,
      ),
      workCompletedAt: toNullableFirestoreTimestamp(domain.workCompletedAt),
      completedAt: toNullableFirestoreTimestamp(
        domain.completedAt ?? domain.workCompletedAt ?? null,
      ),
      completionReviewStartedAt: toNullableFirestoreTimestamp(
        domain.completionReviewStartedAt,
      ),
      readyForInvoicingAt: toNullableFirestoreTimestamp(domain.readyForInvoicingAt),
      invoiceSentAt: toNullableFirestoreTimestamp(domain.invoiceSentAt),
      paidAt: toNullableFirestoreTimestamp(domain.paidAt),
      closedAt: toNullableFirestoreTimestamp(domain.closedAt),
      cancelledAt: toNullableFirestoreTimestamp(domain.cancelledAt),
      holdStartedAt: toNullableFirestoreTimestamp(domain.holdStartedAt),
      escalatedAt: toNullableFirestoreTimestamp(domain.escalatedAt),
    };
  },
};

export const clientInvoiceMapper: FirestoreEntityMapper<
  ClientInvoice,
  ClientInvoiceDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    workOrderId: document.workOrderId,
    clientOrganizationId: document.clientOrganizationId,
    locationId: document.locationId,
    invoiceNumber: document.invoiceNumber,
    lineItems: document.lineItems,
    subtotal: document.subtotal,
    taxAmount: document.taxAmount,
    totalAmount: document.totalAmount,
    currency: document.currency,
    status: document.status,
    issuedDate: toNullableIsoDateTime(document.issuedDate, "issuedDate"),
    dueDate: toIsoDateTime(document.dueDate, "dueDate"),
    sentAt: toNullableIsoDateTime(document.sentAt, "sentAt"),
    viewedAt: toNullableIsoDateTime(document.viewedAt, "viewedAt"),
    paidAt: toNullableIsoDateTime(document.paidAt, "paidAt"),
    voidedAt: toNullableIsoDateTime(document.voidedAt, "voidedAt"),
    paymentReference: document.paymentReference,
    notes: document.notes,
    qboInvoiceId: document.qboInvoiceId,
    qboSyncStatus: document.qboSyncStatus,
    workOrderSnapshot: document.workOrderSnapshot,
    clientSnapshot: document.clientSnapshot,
    locationSnapshot: document.locationSnapshot,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      workOrderId: domain.workOrderId,
      clientOrganizationId: domain.clientOrganizationId,
      locationId: domain.locationId,
      invoiceNumber: domain.invoiceNumber,
      lineItems: domain.lineItems,
      subtotal: domain.subtotal ?? 0,
      taxAmount: domain.taxAmount,
      totalAmount: domain.totalAmount,
      currency: domain.currency,
      status: domain.status,
      issuedDate: toNullableFirestoreTimestamp(domain.issuedDate),
      dueDate: toFirestoreTimestamp(domain.dueDate),
      sentAt: toNullableFirestoreTimestamp(domain.sentAt),
      viewedAt: toNullableFirestoreTimestamp(domain.viewedAt),
      paidAt: toNullableFirestoreTimestamp(domain.paidAt),
      voidedAt: toNullableFirestoreTimestamp(domain.voidedAt),
      paymentReference: domain.paymentReference,
      notes: domain.notes,
      qboInvoiceId: domain.qboInvoiceId,
      qboSyncStatus: domain.qboSyncStatus,
      workOrderSnapshot: domain.workOrderSnapshot,
      clientSnapshot: domain.clientSnapshot,
      locationSnapshot: domain.locationSnapshot,
    };
  },
};

export const contractorQuoteMapper: FirestoreEntityMapper<
  ContractorQuote,
  ContractorQuoteDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    workOrderId: document.workOrderId,
    contractorUserId: document.contractorUserId,
    contractorOrganizationId: document.contractorOrganizationId,
    clientOrganizationId: document.clientOrganizationId,
    locationId: document.locationId,
    lineItems: document.lineItems,
    subtotal: document.subtotal,
    taxAmount: document.taxAmount,
    totalAmount: document.totalAmount,
    notes: document.notes,
    status: document.status,
    submittedAt: toNullableIsoDateTime(document.submittedAt, "submittedAt"),
    reviewedAt: toNullableIsoDateTime(document.reviewedAt, "reviewedAt"),
    reviewedByUserId: document.reviewedByUserId,
    rejectionReason: document.rejectionReason,
    workOrderSnapshot: document.workOrderSnapshot,
    contractorSnapshot: document.contractorSnapshot,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      workOrderId: domain.workOrderId,
      contractorUserId: domain.contractorUserId,
      contractorOrganizationId: domain.contractorOrganizationId,
      clientOrganizationId: domain.clientOrganizationId,
      locationId: domain.locationId,
      lineItems: domain.lineItems,
      subtotal: domain.subtotal ?? 0,
      taxAmount: domain.taxAmount,
      totalAmount: domain.totalAmount,
      notes: domain.notes,
      status: domain.status,
      submittedAt: toNullableFirestoreTimestamp(domain.submittedAt),
      reviewedAt: toNullableFirestoreTimestamp(domain.reviewedAt),
      reviewedByUserId: domain.reviewedByUserId,
      rejectionReason: domain.rejectionReason,
      workOrderSnapshot: domain.workOrderSnapshot,
      contractorSnapshot: domain.contractorSnapshot,
    };
  },
};

export const clientQuoteMapper: FirestoreEntityMapper<
  ClientQuote,
  ClientQuoteDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    workOrderId: document.workOrderId,
    sourceContractorQuoteId: document.sourceContractorQuoteId,
    clientOrganizationId: document.clientOrganizationId,
    locationId: document.locationId,
    lineItems: document.lineItems,
    subtotal: document.subtotal,
    taxAmount: document.taxAmount,
    totalAmount: document.totalAmount,
    notes: document.notes,
    status: document.status,
    sentAt: toNullableIsoDateTime(document.sentAt, "sentAt"),
    respondedAt: toNullableIsoDateTime(document.respondedAt, "respondedAt"),
    approvedAt: toNullableIsoDateTime(document.approvedAt, "approvedAt"),
    rejectedAt: toNullableIsoDateTime(document.rejectedAt, "rejectedAt"),
    rejectionReason: document.rejectionReason,
    createdByUserId: document.createdByUserId,
    workOrderSnapshot: document.workOrderSnapshot,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      workOrderId: domain.workOrderId,
      sourceContractorQuoteId: domain.sourceContractorQuoteId,
      clientOrganizationId: domain.clientOrganizationId,
      locationId: domain.locationId,
      lineItems: domain.lineItems,
      subtotal: domain.subtotal,
      taxAmount: domain.taxAmount,
      totalAmount: domain.totalAmount,
      notes: domain.notes,
      status: domain.status,
      sentAt: toNullableFirestoreTimestamp(domain.sentAt),
      respondedAt: toNullableFirestoreTimestamp(domain.respondedAt),
      approvedAt: toNullableFirestoreTimestamp(domain.approvedAt),
      rejectedAt: toNullableFirestoreTimestamp(domain.rejectedAt),
      rejectionReason: domain.rejectionReason,
      createdByUserId: domain.createdByUserId,
      workOrderSnapshot: domain.workOrderSnapshot,
    };
  },
};

export const assignmentMapper: FirestoreEntityMapper<
  Assignment,
  AssignmentDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    workOrderId: document.workOrderId,
    contractorOrganizationId: document.contractorOrganizationId,
    assigneeType: document.assigneeType,
    assigneeUserId: document.assigneeUserId,
    assigneeOrganizationId: document.assigneeOrganizationId,
    assignedByUserId: document.assignedByUserId,
    status: document.status,
    scheduledDate: toNullableIsoDateTime(document.scheduledDate, "scheduledDate"),
    timeWindowStart: toNullableIsoDateTime(
      document.timeWindowStart,
      "timeWindowStart",
    ),
    timeWindowEnd: toNullableIsoDateTime(document.timeWindowEnd, "timeWindowEnd"),
    assignedAt: toIsoDateTime(document.assignedAt, "assignedAt"),
    acceptedAt: toNullableIsoDateTime(document.acceptedAt, "acceptedAt"),
    declinedAt: toNullableIsoDateTime(document.declinedAt, "declinedAt"),
    completedAt: toNullableIsoDateTime(document.completedAt, "completedAt"),
    notes: document.notes,
    workOrderSnapshot: document.workOrderSnapshot,
    contractorSnapshot: document.contractorSnapshot,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      workOrderId: domain.workOrderId,
      contractorOrganizationId: domain.contractorOrganizationId,
      assigneeType: domain.assigneeType,
      assigneeUserId: domain.assigneeUserId,
      assigneeOrganizationId: domain.assigneeOrganizationId,
      assignedByUserId: domain.assignedByUserId,
      status: domain.status,
      scheduledDate: toNullableFirestoreTimestamp(domain.scheduledDate),
      timeWindowStart: toNullableFirestoreTimestamp(domain.timeWindowStart),
      timeWindowEnd: toNullableFirestoreTimestamp(domain.timeWindowEnd),
      assignedAt: toFirestoreTimestamp(domain.assignedAt),
      acceptedAt: toNullableFirestoreTimestamp(domain.acceptedAt),
      declinedAt: toNullableFirestoreTimestamp(domain.declinedAt),
      completedAt: toNullableFirestoreTimestamp(domain.completedAt),
      notes: domain.notes,
      workOrderSnapshot: domain.workOrderSnapshot,
      contractorSnapshot: domain.contractorSnapshot,
    };
  },
};

export const activityLogMapper: FirestoreEntityMapper<
  ActivityLog,
  ActivityLogDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    workOrderId: document.workOrderId,
    action: document.action,
    eventType: document.eventType,
    message: document.message,
    actorType: document.actorType,
    actorUserId: document.actorUserId,
    actorRole: document.actorRole,
    actor: document.actor,
    resourceType: document.resourceType,
    resourceId: document.resourceId,
    resourceLabel: document.resourceLabel,
    resource: document.resource,
    entityType: document.entityType,
    entityId: document.entityId,
    occurredAt: toIsoDateTime(document.occurredAt, "occurredAt"),
    requestId: document.requestId,
    visibility: document.visibility,
    changes: document.changes,
    metadata: document.metadata,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      workOrderId: domain.workOrderId,
      action: domain.action,
      eventType: domain.eventType,
      message: domain.message,
      actorType: domain.actorType,
      actorUserId: domain.actorUserId,
      actorRole: domain.actorRole,
      actor: domain.actor,
      resourceType: domain.resourceType,
      resourceId: domain.resourceId,
      resourceLabel: domain.resourceLabel,
      resource: domain.resource,
      entityType: domain.entityType,
      entityId: domain.entityId,
      occurredAt: toFirestoreTimestamp(domain.occurredAt),
      requestId: domain.requestId,
      visibility: domain.visibility,
      changes: domain.changes,
      metadata: domain.metadata,
    };
  },
};

export const internalNotificationMapper: FirestoreEntityMapper<
  InternalNotification,
  InternalNotificationDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    recipientUserId: document.recipientUserId,
    recipientRole: document.recipientRole,
    eventType: document.eventType,
    title: document.title,
    message: document.message,
    severity: document.severity,
    status: document.status,
    actor: document.actor,
    entityType: document.entityType,
    entityId: document.entityId,
    workOrderId: document.workOrderId,
    invoiceId: document.invoiceId,
    quoteId: document.quoteId,
    assignmentId: document.assignmentId,
    targetPath: document.targetPath,
    readAt: toNullableIsoDateTime(document.readAt, "readAt"),
    acknowledgedAt: toNullableIsoDateTime(
      document.acknowledgedAt,
      "acknowledgedAt",
    ),
    resolvedAt: toNullableIsoDateTime(document.resolvedAt, "resolvedAt"),
    dueAt: toNullableIsoDateTime(document.dueAt, "dueAt"),
    metadata: document.metadata,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      recipientUserId: domain.recipientUserId,
      recipientRole: domain.recipientRole,
      eventType: domain.eventType,
      title: domain.title,
      message: domain.message,
      severity: domain.severity,
      status: domain.status,
      actor: domain.actor,
      entityType: domain.entityType,
      entityId: domain.entityId,
      workOrderId: domain.workOrderId,
      invoiceId: domain.invoiceId,
      quoteId: domain.quoteId,
      assignmentId: domain.assignmentId,
      targetPath: domain.targetPath,
      readAt: toNullableFirestoreTimestamp(domain.readAt),
      acknowledgedAt: toNullableFirestoreTimestamp(domain.acknowledgedAt),
      resolvedAt: toNullableFirestoreTimestamp(domain.resolvedAt),
      dueAt: toNullableFirestoreTimestamp(domain.dueAt),
      metadata: domain.metadata,
    };
  },
};

export const domainEventMapper: FirestoreEntityMapper<
  DomainEvent,
  DomainEventDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    workOrderId: document.workOrderId ?? null,
    type: document.type,
    actor: document.actor,
    visibility: document.visibility,
    occurredAt: toIsoDateTime(document.occurredAt, "occurredAt"),
    lifecycleStatus: document.lifecycleStatus,
    entity: document.entity,
    summary: document.summary,
    metadata: document.metadata,
    payload: document.payload as DomainEvent["payload"],
  }),
  toDocument: (entity) => {
    const { id, occurredAt, ...domain } = entity;
    void id;
    return {
      ...baseImmutableDocumentFields(domain.organizationId, occurredAt, entity.actor.actorId),
      tenantId: domain.tenantId,
      workOrderId: domain.workOrderId ?? null,
      type: domain.type,
      actor: domain.actor,
      visibility: domain.visibility,
      occurredAt: toFirestoreTimestamp(occurredAt),
      lifecycleStatus: domain.lifecycleStatus,
      entity: domain.entity,
      summary: domain.summary,
      metadata: domain.metadata,
      payload: domain.payload,
    };
  },
};

export const transitionEventMapper: FirestoreEntityMapper<
  TransitionEvent,
  TransitionEventDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    workOrderId: document.workOrderId,
    actor: document.actor,
    visibility: document.visibility,
    occurredAt: toIsoDateTime(document.occurredAt, "occurredAt"),
    fromLifecycleStatus: document.fromLifecycleStatus,
    toLifecycleStatus: document.toLifecycleStatus,
    reason: document.reason,
    metadata: document.metadata,
  }),
  toDocument: (entity) => {
    const { id, occurredAt, ...domain } = entity;
    void id;
    return {
      ...baseImmutableDocumentFields(domain.organizationId, occurredAt, entity.actor.actorId),
      tenantId: domain.tenantId,
      workOrderId: domain.workOrderId,
      actor: domain.actor,
      visibility: domain.visibility,
      occurredAt: toFirestoreTimestamp(occurredAt),
      fromLifecycleStatus: domain.fromLifecycleStatus,
      toLifecycleStatus: domain.toLifecycleStatus,
      reason: domain.reason,
      metadata: domain.metadata,
    };
  },
};

export const transitionAuditMapper: FirestoreEntityMapper<
  TransitionAudit,
  TransitionAuditDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    workOrderId: document.workOrderId,
    actor: document.actor,
    occurredAt: toIsoDateTime(document.occurredAt, "occurredAt"),
    fromLifecycleStatus: document.fromLifecycleStatus,
    toLifecycleStatus: document.toLifecycleStatus,
    reason: document.reason,
    metadata: document.metadata,
    escalationContext: document.escalationContext ?? null,
    holdContext: document.holdContext ?? null,
  }),
  toDocument: (entity) => {
    const { id, occurredAt, ...domain } = entity;
    void id;
    return {
      ...baseImmutableDocumentFields(domain.organizationId, occurredAt, entity.actor.actorId),
      tenantId: domain.tenantId,
      workOrderId: domain.workOrderId,
      actor: domain.actor,
      occurredAt: toFirestoreTimestamp(occurredAt),
      fromLifecycleStatus: domain.fromLifecycleStatus,
      toLifecycleStatus: domain.toLifecycleStatus,
      reason: domain.reason,
      metadata: domain.metadata,
      escalationContext: domain.escalationContext,
      holdContext: domain.holdContext,
    };
  },
};

export const intakeEventMapper: FirestoreEntityMapper<
  IntakeEvent,
  IntakeEventDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    tenantId: document.tenantId,
    status: document.status,
    visibility: document.visibility,
    source: document.source,
    summary: document.summary ?? null,
    relatedWorkOrderId: document.relatedWorkOrderId ?? null,
    artifactIds: document.artifactIds ?? [],
    latestDraftId: document.latestDraftId ?? null,
    latestDecisionId: document.latestDecisionId ?? null,
    receivedAt: toIsoDateTime(document.receivedAt, "receivedAt"),
    createdByActor: document.createdByActor,
  }),
  toDocument: (entity) => {
    const { id, receivedAt, createdAt, updatedAt, ...domain } = entity;
    void id;
    void createdAt;
    void updatedAt;
    return {
      ...toAuditFields(entity),
      tenantId: domain.tenantId,
      status: domain.status,
      visibility: domain.visibility,
      source: domain.source,
      summary: domain.summary ?? null,
      relatedWorkOrderId: domain.relatedWorkOrderId ?? null,
      artifactIds: domain.artifactIds ?? [],
      latestDraftId: domain.latestDraftId ?? null,
      latestDecisionId: domain.latestDecisionId ?? null,
      receivedAt: toFirestoreTimestamp(receivedAt),
      createdByActor: domain.createdByActor,
    };
  },
};

export const intakeArtifactMapper: FirestoreEntityMapper<
  IntakeArtifact,
  IntakeArtifactDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    tenantId: document.tenantId,
    intakeEventId: document.intakeEventId,
    kind: document.kind,
    visibility: document.visibility,
    isImmutable: true,
    source: document.source,
    normalizedContent: document.normalizedContent,
    rawContent: document.rawContent ?? null,
    structuredMetadata: document.structuredMetadata ?? {},
    attachmentReferences: document.attachmentReferences ?? [],
    communicationThreadId: document.communicationThreadId ?? null,
    communicationMessageId: document.communicationMessageId ?? null,
    createdByActor: document.createdByActor,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      tenantId: domain.tenantId,
      intakeEventId: domain.intakeEventId,
      kind: domain.kind,
      visibility: domain.visibility,
      isImmutable: true,
      source: domain.source,
      normalizedContent: domain.normalizedContent,
      rawContent: domain.rawContent ?? null,
      structuredMetadata: domain.structuredMetadata ?? {},
      attachmentReferences: domain.attachmentReferences ?? [],
      communicationThreadId: domain.communicationThreadId ?? null,
      communicationMessageId: domain.communicationMessageId ?? null,
      createdByActor: domain.createdByActor,
    };
  },
};

export const aiIntakeDraftMapper: FirestoreEntityMapper<
  AiIntakeDraft,
  AiIntakeDraftDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    tenantId: document.tenantId,
    intakeEventId: document.intakeEventId,
    artifactIds: document.artifactIds ?? [],
    reviewStatus: document.reviewStatus,
    extractedTitle: document.extractedTitle ?? null,
    extractedDescription: document.extractedDescription ?? null,
    extractedPriority: document.extractedPriority ?? null,
    extractedCategory: document.extractedCategory ?? null,
    extractedLocation: document.extractedLocation ?? null,
    extractedClient: document.extractedClient ?? null,
    extractedContacts: document.extractedContacts ?? [],
    extractedTrade: document.extractedTrade ?? null,
    extractedUrgency: document.extractedUrgency ?? null,
    extractedSuggestedLifecycle: document.extractedSuggestedLifecycle ?? null,
    overallConfidence: document.overallConfidence,
    perFieldConfidence: document.perFieldConfidence ?? {},
    evidence: document.evidence ?? [],
    evidenceReferences: document.evidenceReferences ?? [],
    extractedSnippets: document.extractedSnippets ?? [],
    locationCandidates: document.locationCandidates ?? [],
    contactCandidates: document.contactCandidates ?? [],
    duplicateCandidates: document.duplicateCandidates ?? [],
    workOrderMatchSuggestions: document.workOrderMatchSuggestions ?? [],
    aiModel: document.aiModel,
    aiPromptVersion: document.aiPromptVersion,
    aiRunId: document.aiRunId,
    generatedAt: toIsoDateTime(document.generatedAt, "generatedAt"),
    assignedReviewerUserId: document.assignedReviewerUserId ?? null,
    assignedAt: toNullableIsoDateTime(document.assignedAt, "assignedAt"),
    reviewStartedAt: toNullableIsoDateTime(document.reviewStartedAt, "reviewStartedAt"),
    lastReviewedAt: toNullableIsoDateTime(document.lastReviewedAt, "lastReviewedAt"),
    escalationState: document.escalationState ?? "none",
    escalatedToUserId: document.escalatedToUserId ?? null,
    escalatedAt: toNullableIsoDateTime(document.escalatedAt, "escalatedAt"),
    reviewerUserId: document.reviewerUserId ?? null,
    reviewerDecision: document.reviewerDecision ?? null,
    reviewerNotes: document.reviewerNotes ?? null,
    approvedWorkOrderId: document.approvedWorkOrderId ?? null,
    rejectedReason: document.rejectedReason ?? null,
    mergedIntoWorkOrderId: document.mergedIntoWorkOrderId ?? null,
    createdByActor: document.createdByActor,
  }),
  toDocument: (entity) => {
    const { id, generatedAt, ...domain } = entity;
    void id;
    return {
      ...toAuditFields(domain),
      tenantId: domain.tenantId,
      intakeEventId: domain.intakeEventId,
      artifactIds: domain.artifactIds ?? [],
      reviewStatus: domain.reviewStatus,
      extractedTitle: domain.extractedTitle ?? null,
      extractedDescription: domain.extractedDescription ?? null,
      extractedPriority: domain.extractedPriority ?? null,
      extractedCategory: domain.extractedCategory ?? null,
      extractedLocation: domain.extractedLocation ?? null,
      extractedClient: domain.extractedClient ?? null,
      extractedContacts: domain.extractedContacts ?? [],
      extractedTrade: domain.extractedTrade ?? null,
      extractedUrgency: domain.extractedUrgency ?? null,
      extractedSuggestedLifecycle: domain.extractedSuggestedLifecycle ?? null,
      overallConfidence: domain.overallConfidence,
      perFieldConfidence: domain.perFieldConfidence ?? {},
      evidence: domain.evidence ?? [],
      evidenceReferences: domain.evidenceReferences ?? [],
      extractedSnippets: domain.extractedSnippets ?? [],
      locationCandidates: domain.locationCandidates ?? [],
      contactCandidates: domain.contactCandidates ?? [],
      duplicateCandidates: domain.duplicateCandidates ?? [],
      workOrderMatchSuggestions: domain.workOrderMatchSuggestions ?? [],
      aiModel: domain.aiModel,
      aiPromptVersion: domain.aiPromptVersion,
      aiRunId: domain.aiRunId,
      generatedAt: toFirestoreTimestamp(generatedAt),
      assignedReviewerUserId: domain.assignedReviewerUserId ?? null,
      assignedAt: toNullableFirestoreTimestamp(domain.assignedAt),
      reviewStartedAt: toNullableFirestoreTimestamp(domain.reviewStartedAt),
      lastReviewedAt: toNullableFirestoreTimestamp(domain.lastReviewedAt),
      escalationState: domain.escalationState,
      escalatedToUserId: domain.escalatedToUserId ?? null,
      escalatedAt: toNullableFirestoreTimestamp(domain.escalatedAt),
      reviewerUserId: domain.reviewerUserId ?? null,
      reviewerDecision: domain.reviewerDecision ?? null,
      reviewerNotes: domain.reviewerNotes ?? null,
      approvedWorkOrderId: domain.approvedWorkOrderId ?? null,
      rejectedReason: domain.rejectedReason ?? null,
      mergedIntoWorkOrderId: domain.mergedIntoWorkOrderId ?? null,
      createdByActor: domain.createdByActor,
    };
  },
};

export const intakeApprovalMapper: FirestoreEntityMapper<
  IntakeApproval,
  IntakeApprovalDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    tenantId: document.tenantId,
    intakeEventId: document.intakeEventId,
    aiIntakeDraftId: document.aiIntakeDraftId,
    reviewerUserId: document.reviewerUserId,
    decision: document.decision,
    reviewerNotes: document.reviewerNotes ?? null,
    approvedInput: document.approvedInput ?? null,
    approvedWorkOrderId: document.approvedWorkOrderId ?? null,
    mergedIntoWorkOrderId: document.mergedIntoWorkOrderId ?? null,
    duplicateResolution: document.duplicateResolution ?? {
      candidateIds: [],
      falsePositiveIds: [],
    },
    createdByActor: document.createdByActor,
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      tenantId: domain.tenantId,
      intakeEventId: domain.intakeEventId,
      aiIntakeDraftId: domain.aiIntakeDraftId,
      reviewerUserId: domain.reviewerUserId,
      decision: domain.decision,
      reviewerNotes: domain.reviewerNotes ?? null,
      approvedInput: domain.approvedInput ?? null,
      approvedWorkOrderId: domain.approvedWorkOrderId ?? null,
      mergedIntoWorkOrderId: domain.mergedIntoWorkOrderId ?? null,
      duplicateResolution: domain.duplicateResolution,
      createdByActor: domain.createdByActor,
    };
  },
};

export const intakeDecisionMapper: FirestoreEntityMapper<
  IntakeDecision,
  IntakeDecisionDocument
> = {
  toDomain: (id, document) => ({
    id,
    ...fromAuditFields(document),
    tenantId: document.tenantId,
    intakeEventId: document.intakeEventId,
    aiIntakeDraftId: document.aiIntakeDraftId,
    reviewerUserId: document.reviewerUserId,
    decision: document.decision,
    notes: document.notes ?? null,
    approvedWorkOrderId: document.approvedWorkOrderId ?? null,
    mergedIntoWorkOrderId: document.mergedIntoWorkOrderId ?? null,
    rejectedReason: document.rejectedReason ?? null,
    escalatedToUserId: document.escalatedToUserId ?? null,
    createdByActor: document.createdByActor,
    metadata: document.metadata ?? {},
  }),
  toDocument: (entity) => {
    const domain = omitDocumentId(entity);
    return {
      ...toAuditFields(domain),
      tenantId: domain.tenantId,
      intakeEventId: domain.intakeEventId,
      aiIntakeDraftId: domain.aiIntakeDraftId,
      reviewerUserId: domain.reviewerUserId,
      decision: domain.decision,
      notes: domain.notes ?? null,
      approvedWorkOrderId: domain.approvedWorkOrderId ?? null,
      mergedIntoWorkOrderId: domain.mergedIntoWorkOrderId ?? null,
      rejectedReason: domain.rejectedReason ?? null,
      escalatedToUserId: domain.escalatedToUserId ?? null,
      createdByActor: domain.createdByActor,
      metadata: domain.metadata ?? {},
    };
  },
};

export const communicationThreadMapper: FirestoreEntityMapper<
  CommunicationThread,
  CommunicationThreadDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    workOrderId: document.workOrderId ?? null,
    channel: document.channel,
    subject: document.subject ?? null,
    visibility: document.visibility ?? [],
    participantIds: document.participantIds ?? [],
    relatedEventIds: document.relatedEventIds ?? [],
    linkedEntityIds: document.linkedEntityIds ?? [],
    lastMessageId: document.lastMessageId ?? null,
    lastMessageAt: toNullableIsoDateTime(document.lastMessageAt, "lastMessageAt"),
    externalProvider: document.externalProvider ?? null,
    externalThreadId: document.externalThreadId ?? null,
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    createdByActor: document.createdByActor,
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: entity.createdByActor.actorId ?? "system",
      updatedByUserId: entity.createdByActor.actorId ?? "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    workOrderId: entity.workOrderId ?? null,
    channel: entity.channel,
    subject: entity.subject ?? null,
    visibility: entity.visibility,
    participantIds: entity.participantIds,
    relatedEventIds: entity.relatedEventIds,
    linkedEntityIds: entity.linkedEntityIds,
    lastMessageId: entity.lastMessageId ?? null,
    lastMessageAt: toNullableFirestoreTimestamp(entity.lastMessageAt),
    externalProvider: entity.externalProvider ?? null,
    externalThreadId: entity.externalThreadId ?? null,
    metadata: entity.metadata ?? {},
    createdByActor: entity.createdByActor,
  }),
};

export const communicationMessageMapper: FirestoreEntityMapper<
  CommunicationMessage,
  CommunicationMessageDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    threadId: document.threadId,
    workOrderId: document.workOrderId ?? null,
    referenceMessageId: document.referenceMessageId ?? null,
    channel: document.channel,
    direction: document.direction,
    visibility: document.visibility ?? [],
    subject: document.subject ?? null,
    body: document.body,
    plainTextBody: document.plainTextBody,
    normalizedContent: document.normalizedContent,
    metadata: document.metadata ?? {},
    senderActorId: document.senderActorId ?? null,
    senderActorType: document.senderActorType,
    senderActorRole: document.senderActorRole ?? null,
    participantIds: document.participantIds ?? [],
    clientContactId: document.clientContactId ?? null,
    contractorOrganizationId: document.contractorOrganizationId ?? null,
    linkedEntityIds: document.linkedEntityIds ?? [],
    relatedEventIds: document.relatedEventIds ?? [],
    sentAt: toNullableIsoDateTime(document.sentAt, "sentAt"),
    deliveredAt: toNullableIsoDateTime(document.deliveredAt, "deliveredAt"),
    readAt: toNullableIsoDateTime(document.readAt, "readAt"),
    externalProvider: document.externalProvider ?? null,
    externalThreadId: document.externalThreadId ?? null,
    externalMessageId: document.externalMessageId ?? null,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    createdByActor: document.createdByActor,
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.createdAt,
      createdByUserId: entity.createdByActor.actorId ?? "system",
      updatedByUserId: entity.createdByActor.actorId ?? "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    threadId: entity.threadId,
    workOrderId: entity.workOrderId ?? null,
    referenceMessageId: entity.referenceMessageId ?? null,
    channel: entity.channel,
    direction: entity.direction,
    visibility: entity.visibility,
    subject: entity.subject ?? null,
    body: entity.body,
    plainTextBody: entity.plainTextBody,
    normalizedContent: entity.normalizedContent,
    metadata: entity.metadata ?? {},
    senderActorId: entity.senderActorId ?? null,
    senderActorType: entity.senderActorType,
    senderActorRole: entity.senderActorRole ?? null,
    participantIds: entity.participantIds,
    clientContactId: entity.clientContactId ?? null,
    contractorOrganizationId: entity.contractorOrganizationId ?? null,
    linkedEntityIds: entity.linkedEntityIds,
    relatedEventIds: entity.relatedEventIds,
    sentAt: toNullableFirestoreTimestamp(entity.sentAt),
    deliveredAt: toNullableFirestoreTimestamp(entity.deliveredAt),
    readAt: toNullableFirestoreTimestamp(entity.readAt),
    externalProvider: entity.externalProvider ?? null,
    externalThreadId: entity.externalThreadId ?? null,
    externalMessageId: entity.externalMessageId ?? null,
    createdByActor: entity.createdByActor,
  }),
};

export const communicationParticipantMapper: FirestoreEntityMapper<
  CommunicationParticipant,
  CommunicationParticipantDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    threadId: document.threadId,
    workOrderId: document.workOrderId ?? null,
    actorType: document.actorType,
    userId: document.userId ?? null,
    userRole: document.userRole ?? null,
    contactId: document.contactId ?? null,
    clientOrganizationId: document.clientOrganizationId ?? null,
    contractorOrganizationId: document.contractorOrganizationId ?? null,
    displayName: document.displayName ?? null,
    email: document.email ?? null,
    phone: document.phone ?? null,
    visibility: document.visibility ?? [],
    joinedAt: toIsoDateTime(document.joinedAt, "joinedAt"),
    metadata: document.metadata ?? {},
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.joinedAt,
      updatedAt: entity.joinedAt,
      createdByUserId: entity.userId ?? "system",
      updatedByUserId: entity.userId ?? "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    threadId: entity.threadId,
    workOrderId: entity.workOrderId ?? null,
    actorType: entity.actorType,
    userId: entity.userId ?? null,
    userRole: entity.userRole ?? null,
    contactId: entity.contactId ?? null,
    clientOrganizationId: entity.clientOrganizationId ?? null,
    contractorOrganizationId: entity.contractorOrganizationId ?? null,
    displayName: entity.displayName ?? null,
    email: entity.email ?? null,
    phone: entity.phone ?? null,
    visibility: entity.visibility,
    joinedAt: toFirestoreTimestamp(entity.joinedAt),
    metadata: entity.metadata ?? {},
  }),
};

export const communicationLinkMapper: FirestoreEntityMapper<
  CommunicationLink,
  CommunicationLinkDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    threadId: document.threadId ?? null,
    messageId: document.messageId ?? null,
    workOrderId: document.workOrderId ?? null,
    entityType: document.entityType,
    entityId: document.entityId,
    relationshipType: document.relationshipType,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    createdByActor: document.createdByActor,
    metadata: document.metadata ?? {},
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.createdAt,
      createdByUserId: entity.createdByActor.actorId ?? "system",
      updatedByUserId: entity.createdByActor.actorId ?? "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    threadId: entity.threadId ?? null,
    messageId: entity.messageId ?? null,
    workOrderId: entity.workOrderId ?? null,
    entityType: entity.entityType,
    entityId: entity.entityId,
    relationshipType: entity.relationshipType,
    createdAt: toFirestoreTimestamp(entity.createdAt),
    createdByActor: entity.createdByActor,
    metadata: entity.metadata ?? {},
  }),
};

export const communicationAttachmentMapper: FirestoreEntityMapper<
  CommunicationAttachment,
  CommunicationAttachmentDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    threadId: document.threadId,
    messageId: document.messageId,
    workOrderId: document.workOrderId ?? null,
    fileName: document.fileName,
    contentType: document.contentType ?? null,
    sizeBytes: document.sizeBytes,
    storagePath: document.storagePath,
    hydrationStatus: document.hydrationStatus ?? "not_requested",
    hydratedAt: toNullableIsoDateTime(document.hydratedAt, "hydratedAt"),
    hydrationError: document.hydrationError ?? null,
    contentHash: document.contentHash ?? null,
    visibility: document.visibility ?? [],
    uploadedByActor: document.uploadedByActor,
    externalProvider: document.externalProvider ?? null,
    externalAttachmentId: document.externalAttachmentId ?? null,
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.createdAt,
      createdByUserId: entity.uploadedByActor.actorId ?? "system",
      updatedByUserId: entity.uploadedByActor.actorId ?? "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    threadId: entity.threadId,
    messageId: entity.messageId,
    workOrderId: entity.workOrderId ?? null,
    fileName: entity.fileName,
    contentType: entity.contentType ?? null,
    sizeBytes: entity.sizeBytes,
    storagePath: entity.storagePath,
    hydrationStatus: entity.hydrationStatus,
    hydratedAt: toNullableFirestoreTimestamp(entity.hydratedAt),
    hydrationError: entity.hydrationError ?? null,
    contentHash: entity.contentHash ?? null,
    visibility: entity.visibility,
    uploadedByActor: entity.uploadedByActor,
    externalProvider: entity.externalProvider ?? null,
    externalAttachmentId: entity.externalAttachmentId ?? null,
    metadata: entity.metadata ?? {},
  }),
};

export const communicationMatchSuggestionMapper: FirestoreEntityMapper<
  CommunicationMatchSuggestion,
  CommunicationMatchSuggestionDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    threadId: document.threadId ?? null,
    messageId: document.messageId,
    workOrderId: document.workOrderId ?? null,
    suggestedEntityType: document.suggestedEntityType,
    suggestedEntityId: document.suggestedEntityId,
    confidenceScore: document.confidenceScore,
    status: document.status,
    suggestedAt: toIsoDateTime(document.suggestedAt, "suggestedAt"),
    reviewedAt: toNullableIsoDateTime(document.reviewedAt, "reviewedAt"),
    reviewedByActor: document.reviewedByActor ?? null,
    rationale: document.rationale ?? null,
    metadata: document.metadata ?? {},
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.suggestedAt,
      updatedAt: entity.reviewedAt ?? entity.suggestedAt,
      createdByUserId: entity.reviewedByActor?.actorId ?? "system",
      updatedByUserId: entity.reviewedByActor?.actorId ?? "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    threadId: entity.threadId ?? null,
    messageId: entity.messageId,
    workOrderId: entity.workOrderId ?? null,
    suggestedEntityType: entity.suggestedEntityType,
    suggestedEntityId: entity.suggestedEntityId,
    confidenceScore: entity.confidenceScore,
    status: entity.status,
    suggestedAt: toFirestoreTimestamp(entity.suggestedAt),
    reviewedAt: toNullableFirestoreTimestamp(entity.reviewedAt),
    reviewedByActor: entity.reviewedByActor ?? null,
    rationale: entity.rationale ?? null,
    metadata: entity.metadata ?? {},
  }),
};

export const providerConnectionMapper: FirestoreEntityMapper<
  ProviderConnection,
  ProviderConnectionDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    providerKey: document.providerKey,
    providerTenantId: document.providerTenantId ?? null,
    providerAccountId: document.providerAccountId ?? null,
    mailboxAddress: document.mailboxAddress ?? null,
    displayName: document.displayName ?? null,
    scopes: document.scopes ?? [],
    scopeMetadata: document.scopeMetadata ?? {},
    status: document.status,
    healthStatus: document.healthStatus ?? "unknown",
    ownerUserId: document.ownerUserId ?? null,
    connectedAt: toNullableIsoDateTime(document.connectedAt, "connectedAt"),
    disabledAt: toNullableIsoDateTime(document.disabledAt, "disabledAt"),
    expiresAt: toNullableIsoDateTime(document.expiresAt, "expiresAt"),
    lastHealthyAt: toNullableIsoDateTime(document.lastHealthyAt, "lastHealthyAt"),
    lastError: document.lastError ?? null,
    lastSyncedAt: toNullableIsoDateTime(document.lastSyncedAt, "lastSyncedAt"),
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    providerKey: entity.providerKey,
    providerTenantId: entity.providerTenantId ?? null,
    providerAccountId: entity.providerAccountId ?? null,
    mailboxAddress: entity.mailboxAddress ?? null,
    displayName: entity.displayName ?? null,
    scopes: entity.scopes ?? [],
    scopeMetadata: entity.scopeMetadata ?? {},
    status: entity.status,
    healthStatus: entity.healthStatus,
    ownerUserId: entity.ownerUserId ?? null,
    connectedAt: toNullableFirestoreTimestamp(entity.connectedAt),
    disabledAt: toNullableFirestoreTimestamp(entity.disabledAt),
    expiresAt: toNullableFirestoreTimestamp(entity.expiresAt),
    lastHealthyAt: toNullableFirestoreTimestamp(entity.lastHealthyAt),
    lastError: entity.lastError ?? null,
    lastSyncedAt: toNullableFirestoreTimestamp(entity.lastSyncedAt),
    metadata: entity.metadata ?? {},
  }),
};

export const providerSyncCheckpointMapper: FirestoreEntityMapper<
  ProviderSyncCheckpoint,
  ProviderSyncCheckpointDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    providerKey: document.providerKey,
    providerConnectionId: document.providerConnectionId ?? null,
    checkpointType: document.checkpointType,
    mailboxScope: document.mailboxScope,
    cursor: document.cursor ?? null,
    lastProcessedReceivedAt: toNullableIsoDateTime(
      document.lastProcessedReceivedAt,
      "lastProcessedReceivedAt",
    ),
    lastAttemptedAt: toNullableIsoDateTime(document.lastAttemptedAt, "lastAttemptedAt"),
    lastSuccessfulSyncAt: toNullableIsoDateTime(
      document.lastSuccessfulSyncAt,
      "lastSuccessfulSyncAt",
    ),
    status: document.status,
    failureCount: document.failureCount ?? 0,
    lastError: document.lastError ?? null,
    nextRetryAt: toNullableIsoDateTime(document.nextRetryAt, "nextRetryAt"),
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    providerKey: entity.providerKey,
    providerConnectionId: entity.providerConnectionId ?? null,
    checkpointType: entity.checkpointType,
    mailboxScope: entity.mailboxScope,
    cursor: entity.cursor ?? null,
    lastProcessedReceivedAt: toNullableFirestoreTimestamp(entity.lastProcessedReceivedAt),
    lastAttemptedAt: toNullableFirestoreTimestamp(entity.lastAttemptedAt),
    lastSuccessfulSyncAt: toNullableFirestoreTimestamp(entity.lastSuccessfulSyncAt),
    status: entity.status,
    failureCount: entity.failureCount,
    lastError: entity.lastError ?? null,
    nextRetryAt: toNullableFirestoreTimestamp(entity.nextRetryAt),
    metadata: entity.metadata ?? {},
  }),
};

export const providerSyncRunMapper: FirestoreEntityMapper<
  ProviderSyncRun,
  ProviderSyncRunDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    connectionId: document.connectionId,
    providerKey: document.providerKey,
    mailboxScope: document.mailboxScope,
    startedAt: toIsoDateTime(document.startedAt, "startedAt"),
    completedAt: toNullableIsoDateTime(document.completedAt, "completedAt"),
    status: document.status,
    messagesSeen: document.messagesSeen ?? 0,
    messagesIngested: document.messagesIngested ?? 0,
    duplicatesSkipped: document.duplicatesSkipped ?? 0,
    failures: document.failures ?? 0,
    checkpointBefore: document.checkpointBefore ?? null,
    checkpointAfter: document.checkpointAfter ?? null,
    errorSummary: document.errorSummary ?? null,
    claim: document.claim
      ? {
          claimedBy: document.claim?.claimedBy ?? null,
          claimToken: document.claim?.claimToken ?? null,
          claimVersion: document.claim?.claimVersion ?? 0,
          claimedAt: toNullableIsoDateTime(document.claim?.claimedAt ?? null, "providerSyncRun.claim.claimedAt"),
          leaseExpiresAt: toNullableIsoDateTime(
            document.claim?.leaseExpiresAt ?? null,
            "providerSyncRun.claim.leaseExpiresAt",
          ),
          heartbeatAt: toNullableIsoDateTime(
            document.claim?.heartbeatAt ?? null,
            "providerSyncRun.claim.heartbeatAt",
          ),
          releasedAt: toNullableIsoDateTime(
            document.claim?.releasedAt ?? null,
            "providerSyncRun.claim.releasedAt",
          ),
          reclaimedAt: toNullableIsoDateTime(
            document.claim?.reclaimedAt ?? null,
            "providerSyncRun.claim.reclaimedAt",
          ),
          reclaimedBy: document.claim?.reclaimedBy ?? null,
          reclaimCount: document.claim?.reclaimCount ?? 0,
        }
      : {
          claimedBy: null,
          claimToken: null,
          claimVersion: 0,
          claimedAt: null,
          leaseExpiresAt: null,
          heartbeatAt: null,
          releasedAt: null,
          reclaimedAt: null,
          reclaimedBy: null,
          reclaimCount: 0,
        },
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    connectionId: entity.connectionId,
    providerKey: entity.providerKey,
    mailboxScope: entity.mailboxScope,
    startedAt: toFirestoreTimestamp(entity.startedAt),
    completedAt: toNullableFirestoreTimestamp(entity.completedAt),
    status: entity.status,
    messagesSeen: entity.messagesSeen,
    messagesIngested: entity.messagesIngested,
    duplicatesSkipped: entity.duplicatesSkipped,
    failures: entity.failures,
    checkpointBefore: entity.checkpointBefore ?? null,
    checkpointAfter: entity.checkpointAfter ?? null,
    errorSummary: entity.errorSummary ?? null,
    claim: {
      ...entity.claim,
      claimedAt: toNullableFirestoreTimestamp(entity.claim.claimedAt),
      leaseExpiresAt: toNullableFirestoreTimestamp(entity.claim.leaseExpiresAt),
      heartbeatAt: toNullableFirestoreTimestamp(entity.claim.heartbeatAt),
      releasedAt: toNullableFirestoreTimestamp(entity.claim.releasedAt),
      reclaimedAt: toNullableFirestoreTimestamp(entity.claim.reclaimedAt),
    },
    metadata: entity.metadata ?? {},
  }),
};

export const providerMessageReceiptMapper: FirestoreEntityMapper<
  ProviderMessageReceipt,
  ProviderMessageReceiptDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    providerKey: document.providerKey,
    providerConnectionId: document.providerConnectionId ?? null,
    providerMessageId: document.providerMessageId ?? null,
    internetMessageId: document.internetMessageId ?? null,
    providerThreadId: document.providerThreadId ?? null,
    canonicalThreadId: document.canonicalThreadId ?? null,
    canonicalMessageId: document.canonicalMessageId ?? null,
    intakeEventId: document.intakeEventId ?? null,
    attachmentIds: document.attachmentIds ?? [],
    fingerprint: document.fingerprint,
    status: document.status,
    visibility: document.visibility ?? [],
    receivedAt: toIsoDateTime(document.receivedAt, "receivedAt"),
    processedAt: toIsoDateTime(document.processedAt, "processedAt"),
    failureReason: document.failureReason ?? null,
    reviewedAt: toNullableIsoDateTime(document.reviewedAt, "reviewedAt"),
    reviewedByUserId: document.reviewedByUserId ?? null,
    supersededByReceiptId: document.supersededByReceiptId ?? null,
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.createdAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    providerKey: entity.providerKey,
    providerConnectionId: entity.providerConnectionId ?? null,
    providerMessageId: entity.providerMessageId ?? null,
    internetMessageId: entity.internetMessageId ?? null,
    providerThreadId: entity.providerThreadId ?? null,
    canonicalThreadId: entity.canonicalThreadId ?? null,
    canonicalMessageId: entity.canonicalMessageId ?? null,
    intakeEventId: entity.intakeEventId ?? null,
    attachmentIds: entity.attachmentIds ?? [],
    fingerprint: entity.fingerprint,
    status: entity.status,
    visibility: entity.visibility,
    receivedAt: toFirestoreTimestamp(entity.receivedAt),
    processedAt: toFirestoreTimestamp(entity.processedAt),
    failureReason: entity.failureReason ?? null,
    reviewedAt: toNullableFirestoreTimestamp(entity.reviewedAt),
    reviewedByUserId: entity.reviewedByUserId ?? null,
    supersededByReceiptId: entity.supersededByReceiptId ?? null,
    metadata: entity.metadata ?? {},
  }),
};

export const workerJobMapper: FirestoreEntityMapper<WorkerJob, WorkerJobDocument> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    type: document.type,
    status: document.status,
    payload: document.payload ?? {},
    payloadVersion: document.payloadVersion,
    idempotencyKey: document.idempotencyKey,
    correlationId: document.correlationId,
    causationId: document.causationId,
    sourceEventId: document.sourceEventId ?? null,
    attemptCount: document.attemptCount ?? 0,
    maxAttempts: document.maxAttempts ?? 1,
    runAfter: toIsoDateTime(document.runAfter, "runAfter"),
    leasedBy: document.leasedBy ?? null,
    leaseExpiresAt: toNullableIsoDateTime(document.leaseExpiresAt, "leaseExpiresAt"),
    lease: document.lease
      ? {
          workerId: document.lease.workerId ?? document.leasedBy ?? null,
          claimToken: document.lease.claimToken ?? null,
          leaseVersion: document.lease.leaseVersion ?? 0,
          claimedAt: toNullableIsoDateTime(document.lease.claimedAt, "lease.claimedAt"),
          leaseExpiresAt: toNullableIsoDateTime(
            document.lease.leaseExpiresAt,
            "lease.leaseExpiresAt",
          ),
          heartbeatAt: toNullableIsoDateTime(document.lease.heartbeatAt, "lease.heartbeatAt"),
          reclaimedAt: toNullableIsoDateTime(document.lease.reclaimedAt, "lease.reclaimedAt"),
          reclaimedBy: document.lease.reclaimedBy ?? null,
          reclaimCount: document.lease.reclaimCount ?? 0,
        }
      : {
          workerId: document.leasedBy ?? null,
          claimToken: null,
          leaseVersion: 0,
          claimedAt: null,
          leaseExpiresAt: toNullableIsoDateTime(document.leaseExpiresAt, "leaseExpiresAt"),
          heartbeatAt: null,
          reclaimedAt: null,
          reclaimedBy: null,
          reclaimCount: 0,
        },
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
    lastError: document.lastError ?? null,
    completedAt: toNullableIsoDateTime(document.completedAt, "completedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    type: entity.type,
    status: entity.status,
    payload: entity.payload,
    payloadVersion: entity.payloadVersion,
    idempotencyKey: entity.idempotencyKey,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    sourceEventId: entity.sourceEventId ?? null,
    attemptCount: entity.attemptCount,
    maxAttempts: entity.maxAttempts,
    runAfter: toFirestoreTimestamp(entity.runAfter),
    leasedBy: entity.leasedBy ?? null,
    leaseExpiresAt: toNullableFirestoreTimestamp(entity.leaseExpiresAt),
    lease: {
      ...entity.lease,
      claimedAt: toNullableFirestoreTimestamp(entity.lease.claimedAt),
      leaseExpiresAt: toNullableFirestoreTimestamp(entity.lease.leaseExpiresAt),
      heartbeatAt: toNullableFirestoreTimestamp(entity.lease.heartbeatAt),
      reclaimedAt: toNullableFirestoreTimestamp(entity.lease.reclaimedAt),
    },
    lastError: entity.lastError ?? null,
    completedAt: toNullableFirestoreTimestamp(entity.completedAt),
  }),
};

export const workerDeadLetterMapper: FirestoreEntityMapper<
  WorkerDeadLetterRecord,
  WorkerDeadLetterDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    originalJobId: document.originalJobId,
    jobType: document.jobType,
    payloadSnapshot: document.payloadSnapshot ?? null,
    payloadReference: document.payloadReference ?? null,
    errorSummary: document.errorSummary,
    finalAttemptCount: document.finalAttemptCount ?? 0,
    correlationId: document.correlationId,
    causationId: document.causationId,
    sourceEventId: document.sourceEventId ?? null,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.createdAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    originalJobId: entity.originalJobId,
    jobType: entity.jobType,
    payloadSnapshot: entity.payloadSnapshot ?? null,
    payloadReference: entity.payloadReference ?? null,
    errorSummary: entity.errorSummary,
    finalAttemptCount: entity.finalAttemptCount,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    sourceEventId: entity.sourceEventId ?? null,
  }),
};

export const slaTimerMapper: FirestoreEntityMapper<SlaTimer, SlaTimerDocument> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    type: document.type,
    targetEntityType: document.targetEntityType,
    targetEntityId: document.targetEntityId,
    status: document.status,
    dueAt: toIsoDateTime(document.dueAt, "dueAt"),
    policyVersion: document.policyVersion,
    payloadVersion: document.payloadVersion,
    condition: document.condition,
    sourceEventId: document.sourceEventId,
    correlationId: document.correlationId,
    causationId: document.causationId,
    idempotencyKey: document.idempotencyKey,
    runtimeJobId: document.runtimeJobId ?? null,
    evaluatedAt: toNullableIsoDateTime(document.evaluatedAt, "evaluatedAt"),
    satisfiedAt: toNullableIsoDateTime(document.satisfiedAt, "satisfiedAt"),
    breachedAt: toNullableIsoDateTime(document.breachedAt, "breachedAt"),
    cancelledAt: toNullableIsoDateTime(document.cancelledAt, "cancelledAt"),
    failureReason: document.failureReason ?? null,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    type: entity.type,
    targetEntityType: entity.targetEntityType,
    targetEntityId: entity.targetEntityId,
    status: entity.status,
    dueAt: toFirestoreTimestamp(entity.dueAt),
    policyVersion: entity.policyVersion,
    payloadVersion: entity.payloadVersion,
    condition: entity.condition,
    sourceEventId: entity.sourceEventId,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    idempotencyKey: entity.idempotencyKey,
    runtimeJobId: entity.runtimeJobId ?? null,
    evaluatedAt: toNullableFirestoreTimestamp(entity.evaluatedAt),
    satisfiedAt: toNullableFirestoreTimestamp(entity.satisfiedAt),
    breachedAt: toNullableFirestoreTimestamp(entity.breachedAt),
    cancelledAt: toNullableFirestoreTimestamp(entity.cancelledAt),
    failureReason: entity.failureReason ?? null,
  }),
};

export const slaScanCursorMapper: FirestoreEntityMapper<
  SlaScanCursor,
  SlaScanCursorDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    scanType: document.scanType,
    timerType: document.timerType ?? null,
    lastScannedDueAt: toNullableIsoDateTime(document.lastScannedDueAt, "lastScannedDueAt"),
    lastScannedId: document.lastScannedId ?? null,
    lastCompletedAt: toNullableIsoDateTime(document.lastCompletedAt, "lastCompletedAt"),
    status: document.status,
    correlationId: document.correlationId,
    recentRuns: document.recentRuns ?? [],
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    scanType: entity.scanType,
    timerType: entity.timerType ?? null,
    lastScannedDueAt: toNullableFirestoreTimestamp(entity.lastScannedDueAt),
    lastScannedId: entity.lastScannedId ?? null,
    lastCompletedAt: toNullableFirestoreTimestamp(entity.lastCompletedAt),
    status: entity.status,
    correlationId: entity.correlationId,
    recentRuns: [...entity.recentRuns],
  }),
};

export const eventProcessingMapper: FirestoreEntityMapper<
  EventProcessingRecord,
  EventProcessingDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    subscriberKey: document.subscriberKey,
    subscriberName: document.subscriberName,
    sourceEventId: document.sourceEventId,
    eventType: document.eventType,
    correlationId: document.correlationId,
    causationId: document.causationId,
    idempotencyKey: document.idempotencyKey,
    status: document.status,
    attemptCount: document.attemptCount ?? 0,
    jobCount: document.jobCount ?? 0,
    jobs: document.jobs ?? [],
    lastError: document.lastError ?? null,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
    completedAt: toNullableIsoDateTime(document.completedAt, "completedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    subscriberKey: entity.subscriberKey,
    subscriberName: entity.subscriberName,
    sourceEventId: entity.sourceEventId,
    eventType: entity.eventType,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    idempotencyKey: entity.idempotencyKey,
    status: entity.status,
    attemptCount: entity.attemptCount,
    jobCount: entity.jobCount,
    jobs: [...entity.jobs],
    lastError: entity.lastError ?? null,
    completedAt: toNullableFirestoreTimestamp(entity.completedAt),
  }),
};

export const deliveryPlanMapper: FirestoreEntityMapper<
  CanonicalDeliveryPlan,
  DeliveryPlanDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    deliveryType: document.deliveryType,
    sourceEscalationId: document.sourceEscalationId,
    sourceEscalationStageNumber: document.sourceEscalationStageNumber ?? null,
    sourceEventId: document.sourceEventId,
    correlationId: document.correlationId,
    causationId: document.causationId,
    idempotencyKey: document.idempotencyKey,
    targetEntityType: document.targetEntityType,
    targetEntityId: document.targetEntityId,
    recipientType: document.recipientType,
    recipientId: document.recipientId,
    recipientAddress: document.recipientAddress,
    channel: document.channel,
    templateId: document.templateId,
    templateVersion: document.templateVersion,
    priority: document.priority,
    status: document.status,
    retryCount: document.retryCount ?? 0,
    nextAttemptAt: toNullableIsoDateTime(document.nextAttemptAt, "nextAttemptAt"),
    suppressionReason: document.suppressionReason ?? null,
    cancellationReason: document.cancellationReason ?? null,
    activeRuntimeJobId: document.activeRuntimeJobId ?? null,
    noopCount: document.noopCount ?? 0,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    deliveryType: entity.deliveryType,
    sourceEscalationId: entity.sourceEscalationId,
    sourceEscalationStageNumber: entity.sourceEscalationStageNumber ?? null,
    sourceEventId: entity.sourceEventId,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    idempotencyKey: entity.idempotencyKey,
    targetEntityType: entity.targetEntityType,
    targetEntityId: entity.targetEntityId,
    recipientType: entity.recipientType,
    recipientId: entity.recipientId,
    recipientAddress: entity.recipientAddress,
    channel: entity.channel,
    templateId: entity.templateId,
    templateVersion: entity.templateVersion,
    priority: entity.priority,
    status: entity.status,
    retryCount: entity.retryCount,
    nextAttemptAt: toNullableFirestoreTimestamp(entity.nextAttemptAt),
    suppressionReason: entity.suppressionReason ?? null,
    cancellationReason: entity.cancellationReason ?? null,
    activeRuntimeJobId: entity.activeRuntimeJobId ?? null,
    noopCount: entity.noopCount,
  }),
};

export const deliveryAttemptMapper: FirestoreEntityMapper<
  DeliveryAttempt,
  DeliveryAttemptDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    deliveryPlanId: document.deliveryPlanId,
    deliveryType: document.deliveryType,
    channel: document.channel,
    adapterType: document.adapterType,
    sourceEventId: document.sourceEventId,
    correlationId: document.correlationId,
    causationId: document.causationId,
    idempotencyKey: document.idempotencyKey,
    status: document.status,
    providerMessageId: document.providerMessageId ?? null,
    providerCorrelationId: document.providerCorrelationId ?? null,
    providerReceiptId: document.providerReceiptId ?? null,
    retryCount: document.retryCount ?? 0,
    nextRetryAt: toNullableIsoDateTime(document.nextRetryAt, "nextRetryAt"),
    executionStartedAt: toNullableIsoDateTime(document.executionStartedAt, "executionStartedAt"),
    executionCompletedAt: toNullableIsoDateTime(document.executionCompletedAt, "executionCompletedAt"),
    failureCode: document.failureCode ?? null,
    failureReason: document.failureReason ?? null,
    emittedEventIds: [...(document.emittedEventIds ?? [])],
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    deliveryPlanId: entity.deliveryPlanId,
    deliveryType: entity.deliveryType,
    channel: entity.channel,
    adapterType: entity.adapterType,
    sourceEventId: entity.sourceEventId,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    idempotencyKey: entity.idempotencyKey,
    status: entity.status,
    providerMessageId: entity.providerMessageId ?? null,
    providerCorrelationId: entity.providerCorrelationId ?? null,
    providerReceiptId: entity.providerReceiptId ?? null,
    retryCount: entity.retryCount,
    nextRetryAt: toNullableFirestoreTimestamp(entity.nextRetryAt),
    executionStartedAt: toNullableFirestoreTimestamp(entity.executionStartedAt),
    executionCompletedAt: toNullableFirestoreTimestamp(entity.executionCompletedAt),
    failureCode: entity.failureCode ?? null,
    failureReason: entity.failureReason ?? null,
    emittedEventIds: [...entity.emittedEventIds],
  }),
};

export const escalationOrchestrationMapper: FirestoreEntityMapper<
  EscalationOrchestration,
  EscalationOrchestrationDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    escalationType: document.escalationType,
    targetEntityType: document.targetEntityType,
    targetEntityId: document.targetEntityId,
    sourceSlaTimerId: document.sourceSlaTimerId,
    sourceEventId: document.sourceEventId,
    correlationId: document.correlationId,
    causationId: document.causationId,
    idempotencyKey: document.idempotencyKey,
    status: document.status,
    currentStage: document.currentStage ?? null,
    stageHistory: (document.stageHistory ?? []).map((stage) => ({
      ...stage,
      emittedEventIds: [...stage.emittedEventIds],
      scheduledRuntimeJobIds: [...stage.scheduledRuntimeJobIds],
    })),
    activeRuntimeJobId: document.activeRuntimeJobId ?? null,
    nextStageAt: toNullableIsoDateTime(document.nextStageAt, "nextStageAt"),
    suppressedReason: document.suppressedReason ?? null,
    cancellationReason: document.cancellationReason ?? null,
    resolvedAt: toNullableIsoDateTime(document.resolvedAt, "resolvedAt"),
    lastProgressedAt: toNullableIsoDateTime(document.lastProgressedAt, "lastProgressedAt"),
    progressionAttemptCount: document.progressionAttemptCount ?? 0,
    noopCount: document.noopCount ?? 0,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    escalationType: entity.escalationType,
    targetEntityType: entity.targetEntityType,
    targetEntityId: entity.targetEntityId,
    sourceSlaTimerId: entity.sourceSlaTimerId,
    sourceEventId: entity.sourceEventId,
    correlationId: entity.correlationId,
    causationId: entity.causationId,
    idempotencyKey: entity.idempotencyKey,
    status: entity.status,
    currentStage: entity.currentStage ?? null,
    stageHistory: entity.stageHistory.map((stage): EscalationStage => ({
      ...stage,
      emittedEventIds: [...stage.emittedEventIds],
      scheduledRuntimeJobIds: [...stage.scheduledRuntimeJobIds],
    })),
    activeRuntimeJobId: entity.activeRuntimeJobId ?? null,
    nextStageAt: toNullableFirestoreTimestamp(entity.nextStageAt),
    suppressedReason: entity.suppressedReason ?? null,
    cancellationReason: entity.cancellationReason ?? null,
    resolvedAt: toNullableFirestoreTimestamp(entity.resolvedAt),
    lastProgressedAt: toNullableFirestoreTimestamp(entity.lastProgressedAt),
    progressionAttemptCount: entity.progressionAttemptCount,
    noopCount: entity.noopCount,
  }),
};

export const providerThreadMappingMapper: FirestoreEntityMapper<
  ProviderThreadMapping,
  ProviderThreadMappingDocument
> = {
  toDomain: (id, document) => ({
    id,
    organizationId: document.organizationId,
    tenantId: document.tenantId,
    providerKey: document.providerKey,
    providerConnectionId: document.providerConnectionId ?? null,
    providerThreadId: document.providerThreadId,
    canonicalThreadId: document.canonicalThreadId,
    latestProviderMessageId: document.latestProviderMessageId ?? null,
    latestInternetMessageId: document.latestInternetMessageId ?? null,
    latestCanonicalMessageId: document.latestCanonicalMessageId ?? null,
    messageCount: document.messageCount ?? 0,
    threadFingerprint: document.threadFingerprint,
    metadata: document.metadata ?? {},
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
  }),
  toDocument: (entity) => ({
    ...toAuditFields({
      organizationId: entity.organizationId,
      recordStatus: "active",
      isDeleted: false,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      createdByUserId: "system",
      updatedByUserId: "system",
      deletedAt: null,
      deletedByUserId: null,
    }),
    tenantId: entity.tenantId,
    providerKey: entity.providerKey,
    providerConnectionId: entity.providerConnectionId ?? null,
    providerThreadId: entity.providerThreadId,
    canonicalThreadId: entity.canonicalThreadId,
    latestProviderMessageId: entity.latestProviderMessageId ?? null,
    latestInternetMessageId: entity.latestInternetMessageId ?? null,
    latestCanonicalMessageId: entity.latestCanonicalMessageId ?? null,
    messageCount: entity.messageCount,
    threadFingerprint: entity.threadFingerprint,
    metadata: entity.metadata ?? {},
  }),
};

function omitDocumentId<TDomain extends { id: EntityId }>(
  domain: TDomain,
): Omit<TDomain, "id"> {
  const { id, ...document } = domain;
  void id;
  return document;
}

function fromAuditFields(document: FirestoreAuditFields): DomainAuditFields {
  return {
    organizationId: document.organizationId,
    recordStatus: document.recordStatus,
    isDeleted: document.isDeleted,
    createdAt: toIsoDateTime(document.createdAt, "createdAt"),
    updatedAt: toIsoDateTime(document.updatedAt, "updatedAt"),
    createdByUserId: document.createdByUserId,
    updatedByUserId: document.updatedByUserId,
    deletedAt: toNullableIsoDateTime(document.deletedAt, "deletedAt"),
    deletedByUserId: document.deletedByUserId ?? null,
  };
}

function toAuditFields(domain: DomainAuditFields): FirestoreAuditFields {
  return {
    organizationId: domain.organizationId,
    recordStatus: domain.recordStatus,
    isDeleted: domain.isDeleted,
    createdAt: toFirestoreTimestamp(domain.createdAt),
    updatedAt: toFirestoreTimestamp(domain.updatedAt),
    createdByUserId: domain.createdByUserId,
    updatedByUserId: domain.updatedByUserId,
    deletedAt: toNullableFirestoreTimestamp(domain.deletedAt),
    deletedByUserId: domain.deletedByUserId ?? null,
  };
}

function baseImmutableDocumentFields(
  organizationId: EntityId,
  occurredAt: string,
  actorId: EntityId | null,
): FirestoreAuditFields {
  return {
    organizationId,
    recordStatus: "active",
    isDeleted: false,
    createdAt: toFirestoreTimestamp(occurredAt),
    updatedAt: toFirestoreTimestamp(occurredAt),
    createdByUserId: actorId ?? "system",
    updatedByUserId: actorId ?? "system",
    deletedAt: null,
    deletedByUserId: null,
  };
}
