import "server-only";

export {
  FIRESTORE_COLLECTIONS,
  FIRESTORE_COLLECTION_STRATEGY,
  FIRESTORE_ID_CONVENTIONS,
  createFirestoreRepositories,
  toFirestoreTimestamp,
  toIsoDateTime,
  toNullableFirestoreTimestamp,
  toNullableIsoDateTime,
} from "@/server/repositories/firestore";
export type {
  ActivityLog,
  ActivityLogDocument,
  ActivityLogRepository,
  AiIntakeDraftDocument,
  AiIntakeDraftRepository,
  Assignment,
  AssignmentDocument,
  AssignmentRepository,
  ClientOrganizationContactLink,
  ClientOrganizationContactLinkDocument,
  ClientOrganizationContactLinkRepository,
  ClientInvoice,
  ClientInvoiceDocument,
  ClientInvoiceRepository,
  ClientQuote,
  ClientQuoteDocument,
  ClientQuoteRepository,
  ClientOrganization,
  ClientOrganizationDocument,
  ClientOrganizationRepository,
  CommunicationAttachmentDocument,
  CommunicationAttachmentRepository,
  CommunicationLinkDocument,
  CommunicationLinkRepository,
  CommunicationMatchSuggestionDocument,
  CommunicationMatchSuggestionRepository,
  CommunicationMessageDocument,
  CommunicationMessageRepository,
  CommunicationParticipantDocument,
  CommunicationParticipantRepository,
  CommunicationThreadDocument,
  CommunicationThreadRepository,
  Contact,
  ContactDocument,
  ContactRepository,
  ContractorContactLink,
  ContractorContactLinkDocument,
  ContractorContactLinkRepository,
  ContractorQuote,
  ContractorQuoteDocument,
  ContractorQuoteRepository,
  ContractorOrganization,
  ContractorOrganizationDocument,
  ContractorOrganizationRepository,
  DeliveryAttemptDocument,
  DeliveryPlanDocument,
  DomainEventDocument,
  DeliveryAttemptRepository,
  DeliveryPlanRepository,
  DomainEventRepository,
  EscalationOrchestrationDocument,
  EscalationOrchestrationRepository,
  EventProcessingDocument,
  EventProcessingRepository,
  EntityRepository,
  FirestoreAuditFields,
  FirestoreCollectionName,
  FirestoreContractorOrganizationStatus,
  FirestoreOrganizationStatus,
  FirestoreRepositories,
  FirestoreTimestampValue,
  InternalNotification,
  InternalNotificationDocument,
  InternalNotificationRepository,
  IntakeApprovalDocument,
  IntakeApprovalRepository,
  IntakeArtifactDocument,
  IntakeArtifactRepository,
  IntakeDecisionDocument,
  IntakeDecisionRepository,
  IntakeEventDocument,
  IntakeEventRepository,
  Location,
  LocationContactLink,
  LocationContactLinkDocument,
  LocationContactLinkRepository,
  LocationDocument,
  LocationRepository,
  ProviderConnectionDocument,
  ProviderConnectionRepository,
  ProviderMessageReceiptDocument,
  ProviderMessageReceiptRepository,
  ProviderSyncCheckpointDocument,
  ProviderSyncCheckpointRepository,
  ProviderSyncRunDocument,
  ProviderSyncRunRepository,
  ProviderThreadMappingDocument,
  ProviderThreadMappingRepository,
  SlaScanCursorDocument,
  SlaScanCursorRepository,
  SlaTimerDocument,
  SlaTimerRepository,
  WorkerDeadLetterDocument,
  WorkerDeadLetterRepository,
  WorkerJobDocument,
  WorkerJobRepository,
  RepositoryListOptions,
  RepositoryListResult,
  RepositoryMutationResult,
  TransitionAuditDocument,
  TransitionAuditRepository,
  TransitionEventDocument,
  TransitionEventRepository,
  UserProfile,
  UserProfileDocument,
  UserProfileRepository,
  WorkOrder,
  WorkOrderDocument,
  WorkOrderRepository,
} from "@/server/repositories/firestore";
export type { DomainEvent, TransitionAudit, TransitionEvent } from "@/server/events/types";
export type {
  CommunicationAttachment,
  CommunicationLink,
  CommunicationMatchSuggestion,
  CommunicationMessage,
  CommunicationParticipant,
  CommunicationThread,
} from "@/modules/communications";
export type {
  AiIntakeDraft,
  IntakeApproval,
  IntakeArtifact,
  IntakeDecision,
  IntakeEvent,
} from "@/modules/intake";
export type {
  NormalizedEmailAddress,
  NormalizedEmailMessage,
  NormalizedEmailThread,
  ProviderAttachmentReference,
  ProviderConnection,
  ProviderMessageReceipt,
  ProviderSyncCheckpoint,
  ProviderSyncRun,
  ProviderThreadMapping,
} from "@/modules/providers";
export type { EventProcessingRecord, WorkerDeadLetterRecord, WorkerJob } from "@/modules/runtime";
export type { DeliveryPlan } from "@/modules/delivery";
export type { EscalationOrchestration } from "@/modules/escalation";
export type { DeliveryAttempt } from "@/modules/transport";
export type { SlaScanCursor, SlaTimer } from "@/modules/sla";
