export const workOrdersModule = {
  name: "work-orders",
  routeBasePath: "/work-orders",
} as const;

export {
  canAssignmentTransition,
  canManageAssignments,
  canOverrideAssignmentCompletion,
  getContractorAssignmentEligibility,
  isActiveAssignmentStatus,
  isTerminalAssignmentWorkOrderStatus,
} from "./domain/assignment-rules.ts";
export {
  getAllowedNextWorkOrderLifecycleStatuses,
  getWorkOrderLifecycleLabel,
  isTerminalWorkOrderLifecycleStatus,
  isWorkOrderLifecycleTransitionAllowed,
  validateWorkOrderLifecycleTransition,
  WORK_ORDER_LIFECYCLE_LABELS,
  WORK_ORDER_LIFECYCLE_STATUSES,
  WORK_ORDER_LIFECYCLE_TRANSITIONS,
  type WorkOrderLifecycleStatus,
  type WorkOrderLifecycleTransitionContext,
} from "./domain/lifecycle.ts";
export {
  ASSIGNMENT_ASSIGNEE_TYPES,
  ASSIGNMENT_STATUS_LABELS,
  ASSIGNMENT_STATUSES,
  WORK_ORDER_CATEGORIES,
  WORK_ORDER_CATEGORY_LABELS,
  WORK_ORDER_PRIORITIES,
  WORK_ORDER_PRIORITY_LABELS,
  WORK_ORDER_SOURCES,
  WORK_ORDER_STATUSES,
  WORK_ORDER_STATUS_LABELS,
  getWorkOrderCategoryLabel,
  getWorkOrderPriorityLabel,
  getWorkOrderStatusLabel,
} from "./domain/constants.ts";
export {
  acceptAssignmentSchema,
  assignmentAssigneeTypeSchema,
  assignmentStatusSchema,
  completeAssignmentSchema,
  createContractorAssignmentSchema,
  createAssignmentSchema,
  createWorkOrderAttachmentMetadataSchema,
  createWorkOrderNoteSchema,
  createWorkOrderSchema,
  declineAssignmentSchema,
  reassignAssignmentSchema,
  reassignContractorAssignmentSchema,
  updateWorkOrderStatusSchema,
  workOrderCategorySchema,
  workOrderListQuerySchema,
  workOrderPrioritySchema,
  workOrderSourceSchema,
  workOrderStatusTransitionWithAssignmentSchema,
  workOrderStatusSchema,
} from "./domain/schemas.ts";
export {
  getAllowedNextWorkOrderStatuses,
  isWorkOrderStatusTransitionAllowed,
  WORK_ORDER_STATUS_TRANSITION_MAP,
} from "./domain/transitions.ts";
export type {
  AcceptAssignmentDto,
  Assignment,
  CompleteAssignmentDto,
  CreateContractorAssignmentDto,
  CreateAssignmentDto,
  CreateWorkOrderAttachmentMetadataDto,
  CreateWorkOrderDto,
  CreateWorkOrderNoteDto,
  DeclineAssignmentDto,
  ReassignAssignmentDto,
  ReassignContractorAssignmentDto,
  UpdateWorkOrderStatusDto,
  WorkOrderActionAvailability,
  WorkOrder,
  WorkOrderAttachment,
  WorkOrderDetail,
  WorkOrderListItem,
  WorkOrderListQuery,
  WorkOrderListQueryDto,
  WorkOrderNote,
  WorkOrderStatusTransitionWithAssignmentDto,
} from "./domain/types.ts";
export type {
  AssignmentAssigneeType,
  AssignmentStatus,
  WorkOrderCategory,
  WorkOrderPriority,
  WorkOrderSource,
  WorkOrderStatus,
} from "./domain/constants.ts";
